spring:
  application:
    name: SPRING-ZABFORREDIS
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: aa18473467841
  redis:
    host: 127.0.0.1
    port: 6379
    password: '123456'
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 20
        min-idle: 0
    timeout: 1000
    database: 0

server:
  port: 7781


exclude:
  url: /login,/regist,/error